package compiler

import (
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Configure the owned generated file and its Go package name.
type WriteOptions struct {
	Dir     string
	Package string
}

// Generate a static Bundle factory that imports only the lightweight runtime.
func (r *Result) generated(options WriteOptions) ([]byte, error) {
	name := options.Package
	if name == "" {
		name = "apidoc"
	}
	if !token.IsIdentifier(name) {
		return nil, fmt.Errorf("openapi.generate.package: invalid Go package name")
	}
	source := "// Code generated by openapi/compiler. DO NOT EDIT.\n// Generate static contracts from source without importing or executing business handlers.\npackage " + name + "\n\nimport \"github.com/openapi-golang/openapi\"\n\n// Store a deterministic versioned contract.\nconst encodedBundle = " + strconv.Quote(string(r.Bundle.JSON())) + "\n\n// Return the static contract and let startup Build report compatibility errors explicitly.\nfunc Bundle() openapi.Bundle { return openapi.GeneratedBundle(encodedBundle) }\n"
	return format.Source([]byte(source))
}

// Atomically update owned output and refuse to overwrite handwritten files.
func (r *Result) Write(options WriteOptions) error {
	content, err := r.generated(options)
	if err != nil {
		return err
	}
	target := filepath.Join(options.Dir, "zz_openapi.gen.go")
	if old, err := os.ReadFile(target); err == nil && !strings.HasPrefix(string(old), "// Code generated by openapi/compiler.") {
		return fmt.Errorf("openapi.generate.ownership: file with the same name is not owned by this generator")
	}
	if err = os.MkdirAll(options.Dir, 0755); err != nil {
		return err
	}
	file, err := os.CreateTemp(options.Dir, ".openapi-*")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	if _, err = file.Write(content); err != nil {
		file.Close()
		return err
	}
	if err = file.Chmod(0644); err != nil {
		file.Close()
		return err
	}
	if err = file.Close(); err != nil {
		return err
	}
	return os.Rename(file.Name(), target)
}

// Compare regenerated bytes without modifying the source directory.
func (r *Result) Check(options WriteOptions) error {
	want, err := r.generated(options)
	if err != nil {
		return err
	}
	got, err := os.ReadFile(filepath.Join(options.Dir, "zz_openapi.gen.go"))
	if err != nil {
		return fmt.Errorf("openapi.generate.missing: %w", err)
	}
	if string(got) != string(want) {
		return fmt.Errorf("openapi.generate.stale: source, build conditions, or generation configuration changed; regenerate the output")
	}
	return nil
}
