package compiler

import (
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// 配置唯一生成文件的目录与合法 Go 包名。
type WriteOptions struct {
	Dir     string
	Package string
}

// 生成仅依赖轻量核心的静态 Bundle 工厂。
func (r *Result) generated(options WriteOptions) ([]byte, error) {
	name := options.Package
	if name == "" {
		name = "apidoc"
	}
	if !token.IsIdentifier(name) {
		return nil, fmt.Errorf("openapi.generate.package: 非法 Go 包名")
	}
	source := "// Code generated by openapi/compiler. DO NOT EDIT.\n// 静态契约由源码生成，不导入或执行业务 handler。\npackage " + name + "\n\nimport \"github.com/openapi-golang/openapi\"\n\n// 保存确定性的版本化契约。\nconst encodedBundle = " + strconv.Quote(string(r.Bundle.JSON())) + "\n\n// 返回静态契约，兼容错误由启动层 Build 明确返回。\nfunc Bundle() openapi.Bundle { return openapi.GeneratedBundle(encodedBundle) }\n"
	return format.Source([]byte(source))
}

// 原子更新本工具拥有的文件，拒绝覆盖同名手写文件。
func (r *Result) Write(options WriteOptions) error {
	content, err := r.generated(options)
	if err != nil {
		return err
	}
	target := filepath.Join(options.Dir, "zz_openapi.gen.go")
	if old, err := os.ReadFile(target); err == nil && !strings.HasPrefix(string(old), "// Code generated by openapi/compiler.") {
		return fmt.Errorf("openapi.generate.ownership: 同名文件不属于本生成器")
	}
	if err = os.MkdirAll(options.Dir, 0755); err != nil {
		return err
	}
	file, err := os.CreateTemp(options.Dir, ".openapi-*")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	if _, err = file.Write(content); err != nil {
		file.Close()
		return err
	}
	if err = file.Chmod(0644); err != nil {
		file.Close()
		return err
	}
	if err = file.Close(); err != nil {
		return err
	}
	return os.Rename(file.Name(), target)
}

// 重新生成字节比较新鲜度，不写入业务目录。
func (r *Result) Check(options WriteOptions) error {
	want, err := r.generated(options)
	if err != nil {
		return err
	}
	got, err := os.ReadFile(filepath.Join(options.Dir, "zz_openapi.gen.go"))
	if err != nil {
		return fmt.Errorf("openapi.generate.missing: %w", err)
	}
	if string(got) != string(want) {
		return fmt.Errorf("openapi.generate.stale: 源码、构建条件或生成配置已变化，请重新生成")
	}
	return nil
}
